prevent user from sending empty messages
nioc/xmpp-web pull request #135
Opened 2024-11-04 00:09 UTC by haansn08

Currently, if `hasSendingEnterKey` is enabled, it is possible to mistakenly send an empty message or spam the room with empty messages simply by keeping <kbd>Enter</kbd> pressed. This PR prevents sending a message, when the input is empty.

2024-11-04 03:02 UTC, nioc commented
Hello @haansn08.

Thanks for the PR.
Could you fix the lint errors before merging?

```
Error:   82:42  error  Expected '===' and instead saw '=='             eqeqeq
Error:   83:1   error  Expected indentation of 10 spaces but found 12  indent
Error:   84:1   error  Expected indentation of 10 spaces but found 12  indent
```

2024-11-04 03:04 UTC, nioc requested changes
Hello @haansn08.

Thanks for the PR.
Could you fix the lint errors before merging?

```
Error:   82:42  error  Expected '===' and instead saw '=='             eqeqeq
Error:   83:1   error  Expected indentation of 10 spaces but found 12  indent
Error:   84:1   error  Expected indentation of 10 spaces but found 12  indent
```

2024-11-14 20:18 UTC, merged

2024-11-14 20:36 UTC, nioc commented
🚀 @haansn08 your code is released in 0.10.3.

2024-11-15 11:53 UTC, haansn08 commented
Wow a whole release for this PR! 😳️